footer-links:
  dribbble:
  email: mailto:florian.prive.21@gmail.com
  facebook:
  flickr:
  github: privefl
  instagram:
  linkedin:
  pinterest:
  rss: rss # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: "users/6103040/f-privé" # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/